
// This file has been generated by the GUI designer. Do not modify.
namespace CryptoExchange
{
	public partial class BinanceView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CryptoExchange.BinanceView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CryptoExchange.BinanceView";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
