
// This file has been generated by the GUI designer. Do not modify.
namespace CryptoExchange
{
	public partial class MarketSummary
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry entry1;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CryptoExchange.MarketSummary
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CryptoExchange.MarketSummary";
			// Container child CryptoExchange.MarketSummary.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
            this.entry1.WidthRequest = 100;
            this.hbox1.Add(this.entry1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry1]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("24hr"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("1m"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("3m"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("5m"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("15m"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("30m"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("1h"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("2h"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("4h"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("6h"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("8h"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("12h"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("1d"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("3d"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("1w"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("1M"));
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 5;
			this.hbox1.Add(this.combobox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.combobox1]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add(this.nodeview1);
			this.alignment1.Add(this.GtkScrolledWindow);
			this.vbox2.Add(this.alignment1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
			w6.Position = 1;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.entry1.Changed += new global::System.EventHandler(this.OnEntry1Changed);
			this.combobox1.Changed += new global::System.EventHandler(this.OnCombobox1Changed);
		}
	}
}
