
// This file has been generated by the GUI designer. Do not modify.
namespace CryptoExchange
{
	public partial class PublicTrades
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Image image1;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.ComboBox combobox3;

		private global::Gtk.Label label3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CryptoExchange.PublicTrades
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CryptoExchange.PublicTrades";
			// Container child CryptoExchange.PublicTrades.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.hbox2.Add(this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.hbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label5]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.hbox2.Add(this.label6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label6]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("10"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("20"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("50"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("100"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("500"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("1000"));
			this.combobox3.Name = "combobox3";
			this.combobox3.Active = 4;
			this.hbox2.Add(this.combobox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.combobox3]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Count:");
			this.hbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label3]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add(this.nodeview1);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w8.Position = 1;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.nodeview1.Shown += new global::System.EventHandler(this.OnNodeview1Shown);
		}
	}
}
