
// This file has been generated by the GUI designer. Do not modify.
namespace CryptoExchange
{
	public partial class ExchangeView
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Alignment alignment1;

		private global::CryptoExchange.MarketSummary marketsummary1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.VBox vbox4;

		private global::CryptoExchange.PublicTrades publictrades1;

		private global::Gtk.Notebook notebook1;

		private global::CryptoExchange.PrivateTrades privatetrades1;

		private global::Gtk.Label label1;

		private global::CryptoExchange.Transfers transfersDeposits;

		private global::Gtk.Label label3;

		private global::CryptoExchange.Transfers transfersWithdrawals;

		private global::Gtk.Label label4;

		private global::CryptoExchange.Funds funds1;

		private global::Gtk.Label label5;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.VBox vbox5;

		private global::CryptoExchange.OrderBook orderbook1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CryptoExchange.ExchangeView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CryptoExchange.ExchangeView";
			// Container child CryptoExchange.ExchangeView.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.marketsummary1 = new global::CryptoExchange.MarketSummary();
			this.marketsummary1.WidthRequest = 800;
			this.marketsummary1.Events = ((global::Gdk.EventMask)(256));
			this.marketsummary1.Name = "marketsummary1";
			this.alignment1.Add(this.marketsummary1);
			this.hbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment1]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.publictrades1 = new global::CryptoExchange.PublicTrades();
			this.publictrades1.Events = ((global::Gdk.EventMask)(256));
			this.publictrades1.Name = "publictrades1";
			this.vbox4.Add(this.publictrades1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.publictrades1]));
			w3.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.privatetrades1 = new global::CryptoExchange.PrivateTrades();
			this.privatetrades1.Events = ((global::Gdk.EventMask)(256));
			this.privatetrades1.Name = "privatetrades1";
			this.notebook1.Add(this.privatetrades1);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Open Orders");
			this.notebook1.SetTabLabel(this.privatetrades1, this.label1);
			this.label1.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.transfersDeposits = new global::CryptoExchange.Transfers();
			this.transfersDeposits.Events = ((global::Gdk.EventMask)(256));
			this.transfersDeposits.Name = "transfersDeposits";
			this.notebook1.Add(this.transfersDeposits);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.transfersDeposits]));
			w5.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Deposits");
			this.notebook1.SetTabLabel(this.transfersDeposits, this.label3);
			this.label3.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.transfersWithdrawals = new global::CryptoExchange.Transfers();
			this.transfersWithdrawals.Events = ((global::Gdk.EventMask)(256));
			this.transfersWithdrawals.Name = "transfersWithdrawals";
			this.notebook1.Add(this.transfersWithdrawals);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.transfersWithdrawals]));
			w6.Position = 2;
			// Notebook tab
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Withdrawals");
			this.notebook1.SetTabLabel(this.transfersWithdrawals, this.label4);
			this.label4.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.funds1 = new global::CryptoExchange.Funds();
			this.funds1.Events = ((global::Gdk.EventMask)(256));
			this.funds1.Name = "funds1";
			this.notebook1.Add(this.funds1);
			global::Gtk.Notebook.NotebookChild w7 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.funds1]));
			w7.Position = 3;
			// Notebook tab
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Funds");
			this.notebook1.SetTabLabel(this.funds1, this.label5);
			this.label5.ShowAll();
			this.vbox4.Add(this.notebook1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.notebook1]));
			w8.Position = 1;
			this.vbox3.Add(this.vbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
			w9.Position = 0;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w10.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(1F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.orderbook1 = new global::CryptoExchange.OrderBook();
			this.orderbook1.WidthRequest = 275;
			this.orderbook1.Events = ((global::Gdk.EventMask)(256));
			this.orderbook1.Name = "orderbook1";
			this.vbox5.Add(this.orderbook1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.orderbook1]));
			w11.Position = 0;
			this.alignment4.Add(this.vbox5);
			this.hbox1.Add(this.alignment4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment4]));
			w13.Position = 2;
			w13.Expand = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
