
// This file has been generated by the GUI designer. Do not modify.
namespace CryptoExchange
{
	public partial class OrderBook
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.ComboBox combobox2;

		private global::Gtk.Label label2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CryptoExchange.OrderBook
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CryptoExchange.OrderBook";
			// Container child CryptoExchange.OrderBook.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Merge:");
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("10"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("0"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("4"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("6"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("7"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("8"));
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 1;
			this.hbox1.Add(this.combobox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.combobox1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.combobox2 = global::Gtk.ComboBox.NewText();
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("10"));
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("20"));
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("50"));
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("100"));
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("500"));
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("1000"));
			this.combobox2.Name = "combobox2";
			this.combobox2.Active = 1;
			this.hbox1.Add(this.combobox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.combobox2]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Count:");
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.nodeview1.EnableSearch = false;
			this.GtkScrolledWindow.Add(this.nodeview1);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w7.Position = 1;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.combobox1.Changed += new global::System.EventHandler(this.OnCombobox1Changed);
			this.combobox2.Changed += new global::System.EventHandler(this.OnCombobox2Changed);
		}
	}
}
