
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.ToggleAction mediaPlayAction;

	private global::Gtk.Action propertiesAction;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Toolbar toolbar2;

	private global::Gtk.Notebook notebook1;

	private global::CryptoExchange.BinanceView binanceview1;

	private global::Gtk.Label label2;

	private global::CryptoExchange.DsxView dsxview1;

	private global::Gtk.Label label9;

	private global::CryptoExchange.HuobiView huobiview1;

	private global::Gtk.Label label10;

	private global::Gtk.Alignment alignment9;

	private global::CryptoExchange.BotsView botsview1;

	private global::Gtk.Label label11;

	private global::CryptoExchange.CoinMarketCapView coinmarketcapview1;

	private global::Gtk.Label label13;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.mediaPlayAction = new global::Gtk.ToggleAction("mediaPlayAction", null, null, "gtk-media-play");
		w1.Add(this.mediaPlayAction, null);
		this.propertiesAction = new global::Gtk.Action("propertiesAction", null, null, "gtk-properties");
		w1.Add(this.propertiesAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1280;
		this.DefaultHeight = 720;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar2\'><toolitem name=\'mediaPlayAction\' action=\'mediaPlayAc" +
				"tion\'/><toolitem name=\'propertiesAction\' action=\'propertiesAction\'/></toolbar></" +
				"ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.toolbar2.IconSize = ((global::Gtk.IconSize)(4));
		this.vbox2.Add(this.toolbar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.toolbar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 2;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.binanceview1 = new global::CryptoExchange.BinanceView();
		this.binanceview1.Events = ((global::Gdk.EventMask)(256));
		this.binanceview1.Name = "binanceview1";
		this.notebook1.Add(this.binanceview1);
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Binance");
		this.notebook1.SetTabLabel(this.binanceview1, this.label2);
		this.label2.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.dsxview1 = new global::CryptoExchange.DsxView();
		this.dsxview1.Events = ((global::Gdk.EventMask)(256));
		this.dsxview1.Name = "dsxview1";
		this.notebook1.Add(this.dsxview1);
		global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.dsxview1]));
		w4.Position = 1;
		// Notebook tab
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("DSX");
		this.notebook1.SetTabLabel(this.dsxview1, this.label9);
		this.label9.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.huobiview1 = new global::CryptoExchange.HuobiView();
		this.huobiview1.Events = ((global::Gdk.EventMask)(256));
		this.huobiview1.Name = "huobiview1";
		this.notebook1.Add(this.huobiview1);
		global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.huobiview1]));
		w5.Position = 2;
		// Notebook tab
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Huobi");
		this.notebook1.SetTabLabel(this.huobiview1, this.label10);
		this.label10.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.alignment9 = new global::Gtk.Alignment(0F, 0.5F, 0.1F, 1F);
		this.alignment9.Name = "alignment9";
		// Container child alignment9.Gtk.Container+ContainerChild
		this.botsview1 = new global::CryptoExchange.BotsView();
		this.botsview1.WidthRequest = 300;
		this.botsview1.Events = ((global::Gdk.EventMask)(256));
		this.botsview1.Name = "botsview1";
		this.alignment9.Add(this.botsview1);
		this.notebook1.Add(this.alignment9);
		global::Gtk.Notebook.NotebookChild w7 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.alignment9]));
		w7.Position = 3;
		// Notebook tab
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Bots");
		this.notebook1.SetTabLabel(this.alignment9, this.label11);
		this.label11.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.coinmarketcapview1 = new global::CryptoExchange.CoinMarketCapView();
		this.coinmarketcapview1.Events = ((global::Gdk.EventMask)(256));
		this.coinmarketcapview1.Name = "coinmarketcapview1";
		this.notebook1.Add(this.coinmarketcapview1);
		global::Gtk.Notebook.NotebookChild w8 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.coinmarketcapview1]));
		w8.Position = 4;
		// Notebook tab
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("CoinMarketCap");
		this.notebook1.SetTabLabel(this.coinmarketcapview1, this.label13);
		this.label13.ShowAll();
		this.vbox2.Add(this.notebook1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
		w9.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox2.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.statusbar1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.mediaPlayAction.Toggled += new global::System.EventHandler(this.OnMediaPlayActionToggled);
		this.propertiesAction.Activated += new global::System.EventHandler(this.OnPropertiesActionActivated);
	}
}
