
// This file has been generated by the GUI designer. Do not modify.
namespace CryptoExchange
{
	public partial class DsxView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.ToggleButton togglebutton1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::CryptoExchange.MarketSummary marketsummary1;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.VPaned vpaned1;

		private global::CryptoExchange.PublicTrades publictrades1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.NodeView nodeview3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CryptoExchange.DsxView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CryptoExchange.DsxView";
			// Container child CryptoExchange.DsxView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0F, 0.5F, 0F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.togglebutton1 = new global::Gtk.ToggleButton();
			this.togglebutton1.CanFocus = true;
			this.togglebutton1.Name = "togglebutton1";
			this.togglebutton1.UseUnderline = true;
			this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString("Refresh");
			this.alignment1.Add(this.togglebutton1);
			this.vbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.marketsummary1 = null;
			this.vbox2.Add(this.marketsummary1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.marketsummary1]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 0;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w5 = new global::Gtk.Label();
			w5.Visible = true;
			this.notebook1.Add(w5);
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Deposits");
			this.notebook1.SetTabLabel(w5, this.label1);
			this.label1.ShowAll();
			// Notebook tab
			global::Gtk.Label w6 = new global::Gtk.Label();
			w6.Visible = true;
			this.notebook1.Add(w6);
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Withdrawals");
			this.notebook1.SetTabLabel(w6, this.label2);
			this.label2.ShowAll();
			// Notebook tab
			global::Gtk.Label w7 = new global::Gtk.Label();
			w7.Visible = true;
			this.notebook1.Add(w7);
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Funds");
			this.notebook1.SetTabLabel(w7, this.label3);
			this.label3.ShowAll();
			this.vbox4.Add(this.notebook1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.notebook1]));
			w8.Position = 1;
			this.hbox1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
			w9.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(1F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 127;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.publictrades1 = null;
			this.vpaned1.Add(this.publictrades1);
			global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.publictrades1]));
			w10.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nodeview3 = new global::Gtk.NodeView();
			this.nodeview3.CanFocus = true;
			this.nodeview3.Name = "nodeview3";
			this.GtkScrolledWindow2.Add(this.nodeview3);
			this.vpaned1.Add(this.GtkScrolledWindow2);
			this.alignment2.Add(this.vpaned1);
			this.hbox1.Add(this.alignment2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment2]));
			w14.Position = 2;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w15.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.togglebutton1.Clicked += new global::System.EventHandler(this.OnTogglebutton1Clicked);
		}
	}
}
